// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qswjkfrumxkzqoejiwwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzd2prZnJ1bXhrenFvZWppd3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDM2MzgsImV4cCI6MjA1Nzg3OTYzOH0.y_wf-8SKKsLbZD3PDaqgkUbntEdCXO-PtMp_gIREzng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);